# Generated by Django 4.1 on 2022-09-06 02:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_elo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fen', models.CharField(max_length=100)),
                ('black_player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='black_player', to=settings.AUTH_USER_MODEL)),
                ('white_player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='white_player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
