# Generated by Django 4.1 on 2022-09-06 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.IntegerField(choices=[(0, 'Ongoing'), (1, 'White'), (2, 'Black'), (3, 'Draw')], default=0),
        ),
    ]
