# Generated by Django 4.1 on 2022-09-14 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_match_black_player_alter_match_white_player_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='number_of_matches',
            field=models.IntegerField(default=0),
        ),
    ]
