# Generated by Django 4.1 on 2022-09-14 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_user_number_of_matches'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
