# Generated by Django 4.1 on 2022-09-18 08:02

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_match_black_pocket_alter_match_white_pocket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='black_pocket',
            field=models.JSONField(default=api.models.default_player_pocket),
        ),
        migrations.AlterField(
            model_name='match',
            name='white_pocket',
            field=models.JSONField(default=api.models.default_player_pocket),
        ),
    ]
